### ISSUE TITLE
Version 1.8.1 no longer compatible with Kotlin < 1.8

### ISSUE THREAD

**Issue by scordio** [seratch/notion-sdk-jvm#91]
It seems that version 1.8.1 lost compatibility with Kotlin < 1.8.

I use `notion-sdk-jvm` modules in [`spring-batch-notion`](https://github.com/scordio/spring-batch-notion) and I [cross-build](https://github.com/scordio/spring-batch-notion/blob/61794c38f2c7f28aa67fdd1f39439ee2c363b346/.github/workflows/cross-version.yml#L33-L36) against multiple versions of [Spring Boot](https://github.com/spring-projects/spring-boot) to ensure backward compatibility.

Specifically, scordio/spring-batch-notion#15:
* [Fails with Spring Boot 3.0.0](https://github.com/scordio/spring-batch-notion/actions/runs/5874903972/job/15930377843), which [implicitly uses](https://github.com/spring-projects/spring-boot/blob/v3.0.0/gradle.properties#L7) Kotlin 1.7.21
* [Fails with Spring Boot 3.0.9](https://github.com/scordio/spring-batch-notion/actions/runs/5874903972/job/15930377968), which [implicitly uses](https://github.com/spring-projects/spring-boot/blob/v3.0.9/gradle.properties#L7) Kotlin 1.7.21
* [Works with Spring Boot 3.1.0](https://github.com/scordio/spring-batch-notion/actions/runs/5874903972/job/15930378056), which [implicitly uses](https://github.com/spring-projects/spring-boot/blob/v3.1.0/gradle.properties#L7) Kotlin 1.8.21
* [Works with Spring Boot 3.1.2](https://github.com/scordio/spring-batch-notion/actions/runs/5874903967/job/15930378256) (latest), which [implicitly uses](https://github.com/spring-projects/spring-boot/blob/v3.1.2/gradle.properties#L7) Kotlin 1.8.21

For example, with Spring Boot 3.0.0 / Kotlin 1.7.21, I get the following error when running a unit test that relies on certain `notion-sdk-core` types:

```
java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt

	at notion.api.v1.model.databases.query.sort.QuerySortDirection.<clinit>(QuerySortDirection.kt:7)
	at io.github.scordio.springframework.batch.extensions.notion.Sort$Direction.<clinit>(Sort.java:111)
	at io.github.scordio.springframework.batch.extensions.notion.Sort.<clinit>(Sort.java:33)
	at io.github.scordio.springframework.batch.extensions.notion.SortTests.testToString(SortTests.java:76)
		...
Caused by: java.lang.ClassNotFoundException: kotlin.enums.EnumEntriesKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 88 more
```

Is there anything that could be done to keep backward compatibility at least with Kotlin 1.7?

**Comment by seratch** [comment]
Hi @scordio, thanks for reporting this issue. Perhaps, a possible way to resolve it could be to downgrade Kotlin verison used for building this library to 1.7. That being said, this means this project has to lock Kotlin version for a certain amount of time.

In general, it's not so easy to support multiple binary compatibilities. Also, this library is my personal project I can use only my spare time. So, the best approach for me is to support only the latest minor version (I've upgraded it in a patch release; this should have been done in minor releases though). Woudl it be possible to upgrade your Kotlin version to the latest?

**Comment by scordio** [comment]
Hi @seratch, sure, I can mention that my library requires at least Kotlin 1.8 when used with Spring Boot 3.0, not the default setup but it can work.

One question though: the README mentions
> All Android runtime versions supported by Kotlin 1.5

I assume that statement should be amended, right?

Would you be interested in a GitHub workflow that tries to build your modules with all the Kotlin versions you'd like to support? This would give you an immediate feedback if this happens again and of course you can decide what the minimum supported version should be 🙂

**Comment by seratch** [comment]
Thanks for pointing out the oudated part on README. I just updated it. ✅ 

>Would you be interested in a GitHub workflow that tries to build your modules with all the Kotlin versions you'd like to support? This would give you an immediate feedback if this happens again and of course you can decide what the minimum supported version should be 🙂

Indeed, detecting simple errors like the one you've reported might be achievable in the way you suggested. However, this approach doesn't guarantee the detection of all such errors because binary compatibility issues can arise as runtime exceptions. To catch all possible patterns, unit tests would need to cover every line of code in this library. This is a significant undertaking, and to be honest, I currently don't have the bandwidth or motivation to complete such a task.

For now, I'd like to see how things go with our current strategy of upgrading the Kotlin version for the build process to the latest available. Yet, if we continue to encounter similar issues in the future, I might consider locking the Kotlin version to 1.7 for subsequent releases.

**Comment by scordio** [comment]
I've composed a cross-version pipeline in [this branch](https://github.com/scordio/notion-sdk-jvm/tree/cross-version-ci) and added a unit test for `QuerySortDirection` but it seems I couldn't reproduce the issue I reported above.

I'm out of ideas right now 🤷

**Comment by scordio** [comment]
Oh right, that makes total sense. Thanks 🙂

**Comment by scordio** [comment]
I've been playing with [japicmp](https://siom79.github.io/japicmp/) for detecting binary incompatible changes between 1.8.0 and 1.8.1, here is the summary of the binary incompatible changes ([full report](https://github.com/seratch/notion-sdk-jvm/files/12360105/notion-jvm-core.zip)):

<img width="566" alt="Screenshot 2023-08-16 at 16 06 48" src="https://github.com/seratch/notion-sdk-jvm/assets/26772046/3145eb9d-3f9e-464d-81c2-6e911b271079">

The findings seem to be related to 6f3cd8eb. They basically highlight the fact that any added field will be binary-incompatible due to the constructor changes.

Surprisingly, the change in `QuerySortDirection` was not detected as binary incompatible.

Generating the full report (`onlyBinaryIncompatible=false`), the change in `QuerySortDirection` is reported as safe:

<img width="1351" alt="Japicmp - All changes" src="https://github.com/seratch/notion-sdk-jvm/assets/26772046/5c665da3-2dd0-4e50-9dbc-f25204ed4ddf">

I'm wondering if this is really the case... it's clear that the "new" `QuerySortDirection` is supposed to work only with the proper runtime, which includes the 1.9 `kotlin.enums.EnumEntriesKt`. I'll ask the opinion of the `japicmp` team.

This might be going a bit out of scope but I wanted to share my findings in case you'd like to throw japicmp or any similar tool in the build 🙂

**Comment by seratch** [comment]
Thank you for sharing those insights. In the past, while extensively working on Scala projects, I found MIMA (https://github.com/lightbend/mima) incredibly valuable for detecting binary compatibility issues. While I suspect it might work for non-Scala projects too, I've not had the opportunity to experiment with it in such contexts.

After giving this issue further thought overnight, I believe that as a mitigative measure, it would be prudent for this library to rely on Kotlin 1.7.x for the foreseeable future, especially in light of the Kotlin-related issue discussed here. Also, I'm leaning towards locking the Kotlin version for this project more permanently. I hope this measure will streamline the developer experience in the long run. I plan to proceed with this release later today.

**Comment by scordio** [comment]
Thank you for considering it!

**Comment by seratch** [comment]
This issue is now fixed
